-- ==========================================================
-- SCRIPT DE INICIALIZACIÓN PARA SUPABASE (Trabajo Práctico 4)
-- Copiar y pegar en el SQL Editor de tu proyecto Supabase y presionar 'Run'
-- ==========================================================

-- 1. Crear tabla 'cursos'
CREATE TABLE IF NOT EXISTS cursos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre TEXT NOT NULL,
  profesor TEXT,
  nivel TEXT,
  cupo INTEGER CHECK (cupo >= 1 AND cupo <= 60),
  descripcion TEXT,
  creado_en TIMESTAMPTZ DEFAULT now()
);

-- 2. Habilitar RLS (Row Level Security)
ALTER TABLE cursos ENABLE ROW LEVEL SECURITY;

-- 3. Crear política de lectura provisoria (using (true))
DROP POLICY IF EXISTS "Permitir lectura publica" ON cursos;
CREATE POLICY "Permitir lectura publica"
  ON cursos
  FOR SELECT
  USING (true);

-- 4. Cargar al menos 6 cursos de ejemplo
INSERT INTO cursos (nombre, profesor, nivel, cupo, descripcion)
VALUES 
  ('Programación Web I', 'Lic. Martín Gómez', 'Inicial', 35, 'Introducción al desarrollo web moderno con HTML5 semántico, CSS3 avanzado y fundamentos de JavaScript moderno.'),
  ('React y Ecosistema Frontend', 'Ing. Valeria Ruiz', 'Intermedio', 25, 'Construcción de Single Page Applications con componentes, hooks, React Router, consumo de APIs REST y manejo de estado.'),
  ('Bases de Datos Relacionales y SQL', 'Lic. Carlos Benítez', 'Inicial', 30, 'Modelado entidad-relación, normalización de tablas, consultas SQL complejas, índices y seguridad con políticas RLS.'),
  ('Node.js y Arquitectura Backend', 'Ing. Sofía Morales', 'Avanzado', 20, 'Desarrollo de APIs RESTful con Express, autenticación JWT, middlewares, conexión a bases de datos y buenas prácticas.'),
  ('Diseño UI/UX y Sistemas de Diseño', 'Diseñadora Lucía Fernández', 'Inicial', 40, 'Principios de experiencia de usuario, diseño de interfaces intuitivas, tipografía, paletas de colores y prototipado.'),
  ('DevOps y Despliegue en la Nube', 'Ing. Hernán Rossi', 'Avanzado', 15, 'Contenerización con Docker, integración continua (CI/CD), variables de entorno y despliegue en plataformas cloud modernas.');
